### ISSUE TITLE
Is this possible for use with Raspbian?

### ISSUE THREAD

**Issue by rndmsfree** [bite-your-idols/gamestarter-openelec#2]
First off,  this looks really cool and it's exactly what I've been looking for!

Unfortunately, being a linux noob, I've tried a couple of the "appliance" kodi/linux installs (OE/RaspBMC/etc) and I just don't find them as useful to me as Raspbian - the desktop and all the other stuff make it work better for my purposes.

Is there a way to make gamestarter work with Raspbian/Kodi?

**Comment by bite-your-idols** [comment]
Hi!
This scripts and addons included are prepared and compiled for OpenELEC so it will not work in Raspbian but you can install Retropie which is much better!!
