### ISSUE TITLE
bluez integration ?

### ISSUE THREAD

**Issue by Roughtrade** [bite-your-idols/gamestarter-openelec#3]
I would try to connect a Bluetooth gamepad ( FC30 Pro from 8bitdo )
Do you have any Idea ? I have installed your great Extension to my Openelec. It is possible to pair the controller with openelec. But if i start a snes game with advanced launcher i can not controll the game.

Regards Peter

**Comment by bite-your-idols** [comment]
I can't tell you for sure because I don't have that gamepad. Over bluetooth I can pair a sixaxis controller in openelec and when I start an emulator it works flawlesly... 
Please check if in openelec it is paired right, then when starting emulator a yellow text must display in botton left corner with the name of the controller.

Also, can be that controller plugged with a USB cable? just to check if the controller is compatible with retroarch or it is a bluetooth issue.

**Comment by Roughtrade** [comment]
i have paired the controller in openelec. There is a blue indicator led on the controller and the light is permanent when it is paired. i can see it also wenn i go to tv guide it schows the Controller as a mouse.

Wenn i connect the controller via USB it works perfect with retroarch and the yellow text shows the controller with the right name.

Connected over bluetooth the controller is not recodniced

**Comment by bite-your-idols** [comment]
OK. I think it is related with name assigned by default by retroarch to your gamepad. For example sixaxis is called "PLAYSTATION(R)3 Controller" when connected over bluetooth, but when connected with USB it calls it "Sony PLAYSTATION(R)3 Controller". 

The exact name is how it must be named the config file, located in /storage/emulators/retroarch/configs/joypads.

When starting retroarch with gamepad connected over bluetooth also some yellow text must display in bottom left corner, saying that a not-configured-gampad is connected in port 0, doesn't it?


One tricky method I did once was to start emulator with another gamepad connecetd (or maybe with 8bitdo's with USB), then enter retroarch menu, go to input configurations for player 2, connect the bluetooth gamepad and save a custom config file. After then, open that file and try to edit default config file (the one in /storage/emulators/retroarch/configs/joypads/name_of_your_gamepad.cfg) with correct values for input_driver, input_device, input_vendor_id, and input_product_id.

Tell me if you discover something new.

**Comment by Roughtrade** [comment]
Sorry there is no yellow text when the Controller is paired over openelec :(

**Comment by bite-your-idols** [comment]
I am sorry, I can be something related with OE's bluetooth driver for your device...

Maybe looking for some issue like this in lakka (it uses OE in background)...
Try to update joyconfigs as they say in this issue: https://github.com/libretro/Lakka/issues/260

**Comment by Roughtrade** [comment]
Sorry for my late response, but i had install a vm with windows to update the firmware of the controller. with the latest firmware it works very well. 

Thank you for your support.

Regards Peter

**Comment by bite-your-idols** [comment]
I am glad to hear that!
